on:
  - push
  - pull_request

name: Main

jobs:
  pandoc-with-weasyprint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.11'
      - run: |
          # pip install weasyprint
          git clone https://github.com/Kozea/WeasyPrint.git
          cd WeasyPrint
          pip install .
          cd ..

          mkdir out
          cd docs

          pandoc sample.md -o ../out/sample.html --standalone --table-of-contents
          pandoc sample.md -o ../out/sample.pdf --pdf-engine weasyprint --table-of-contents

          pandoc sample.md -o ../out/sample-with-css-arg.pdf --pdf-engine weasyprint --table-of-contents --css style.css

          pandoc sample-with-css-link.md -o ../out/sample-with-css-link.html --standalone --table-of-contents
          pandoc sample-with-css-link.md -o ../out/sample-with-css-link.pdf --pdf-engine weasyprint --table-of-contents

          pandoc sample-with-css-inline.md -o ../out/sample-with-css-inline.html --standalone --table-of-contents
          pandoc sample-with-css-inline.md -o ../out/sample-with-css-inline.pdf --pdf-engine weasyprint --table-of-contents
      - uses: actions/upload-artifact@v2
        with:
          name: out
          path: out
