on:
  schedule:
    - cron: '*/5 * * * *'

name: Test

jobs:
  recent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - run: |
          date > README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto commit test
          commit_author: GitHub Actions <actions@github.com>
